spring:
  r2dbc:
    url: r2dbc:h2:mem:///statusDB
    username: sa
    password:
  h2:
    console:
      enabled: true
  application:
    name: status-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080