spring:
  r2dbc:
    url: r2dbc:h2:mem:///statusDB
    username:
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: status-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8081