apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: imovel-service
spec:
  selector:
    app: imovel-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: status-service
spec:
  selector:
    app: status-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: veiculo-service
spec:
  selector:
    app: veiculo-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
