services:
  eureka-service:
    build:
      context: ../eureka-service/docker
      dockerfile: Dockerfile
    container_name: EUREKA-SERVER
    image: joaofigueredo/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - dr3at_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  imovel-service:
    build:
      context: ../imovel-service/docker
      dockerfile: Dockerfile
    container_name: IMOVEL-SERVICE
    image: joaofigueredo/imovel-service:latest
    ports:
      - "8082:8082"
    networks:
      - dr3at_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
  status-service:
    build:
      context: ../status-service/docker
      dockerfile: Dockerfile
    image: joaofigueredo/status-service:latest
    ports:
      - "8081:8081"
    networks:
      - dr3at_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
  veiculo-service:
    build:
      context: ../veiculo-service/docker
      dockerfile: Dockerfile
    container_name: VEICULO-SERVICE
    image: joaofigueredo/veiculo-service:latest
    ports:
      - "8083:8083"
    networks:
      - dr3at_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
networks:
  dr3at_network:
    driver: bridge