services:
  #  rabbitmq:
  #    image: rabbitmq:3-management
  #    container_name: RABBIT-SERVER
  #    networks:
  #      - dr3at_network
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"
  eureka-service:
    build:
      context: ../eureka-service/docker
      dockerfile: Dockerfile
    container_name: EUREKA-SERVER
    image: joaofigueredo/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - dr3at_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  imovel-service:
    build:
      context: ../imovel-service/docker
      dockerfile: Dockerfile
    container_name: IMOVEL-SERVICE
    image: joaofigueredo/imovel-service:latest
    ports:
      - "8080:8080"
    networks:
      - dr3at_network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
  #      - mysql-dr3at_network
  status-service:
    build:
      context: ../status-service/docker
      dockerfile: Dockerfile
    container_name: STATUS-SERVICE
    image: joaofigueredo/status-service:latest
    ports:
      - "8080:8081"
    networks:
      - dr3at_network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
  #    deploy:
  #      replicas: 3
  veiculo-service:
    build:
      context: ../veiculo-service/docker
      dockerfile: Dockerfile
    container_name: VEICULO-SERVICE
    image: joaofigueredo/veiculo-service:latest
    ports:
      - "8080:8082"
    networks:
      - dr3at_network
    environment:
      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-service
#    deploy:
#      replicas: 5

#  gateway:
#    build:
#      context: ../gateway/docker
#      dockerfile: Dockerfile
#    image: joaofigueredo/gateway:latest
#    ports:
#      - "8080:8080"
#    networks:
#      - dr3at_network
#    environment:
#      EUREKA_SERVER_URL: http://eureka-service:8761/eureka/
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    depends_on:
#      - eureka-service
#      - auth-service
#      - chefe-service
#      - status-service
#      - notification-service
#      - veiculo-service
#      - usuario-service
networks:
  dr3at_network:
    driver: bridge