name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurando o JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Instalar dependências e compilar o projeto
      - name: Build with Maven
        run: mvn install -DskipTests

      # Executar os testes
      - name: Run tests
        run: mvn test