name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurando o JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Build eureka-service
      - name: Build eureka-service with Maven
        working-directory: ./eureka-service
        run: mvn install -DskipTests

      - name: Test eureka-service with Maven
        working-directory: ./eureka-service
        run: mvn test

      # Build imovel-service
      - name: Build imovel-service with Maven
        working-directory: ./imovel-service
        run: mvn install -DskipTests

      - name: Test imovel-service with Maven
        working-directory: ./imovel-service
        run: mvn test

      # Build status-service
      - name: Build status-service with Maven
        working-directory: ./status-service
        run: mvn install -DskipTests

      - name: Test status-service with Maven
        working-directory: ./status-service
        run: mvn test

      # Build veiculo-service
      - name: Build veiculo-service with Maven
        working-directory: ./veiculo-service
        run: mvn install -DskipTests

      - name: Test veiculo-service with Maven
        working-directory: ./veiculo-service
        run: mvn test
